// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://azpjccmqhamahfbmfnpb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF6cGpjY21xaGFtYWhmYm1mbnBiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0NDUzMDcsImV4cCI6MjA1OTAyMTMwN30.lB_vPc-toORzx9kl7NchmR3X_UxWw0Ca6-TIOKKtJfo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);