// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://loiigifcvnfunogmqgcg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxvaWlnaWZjdm5mdW5vZ21xZ2NnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2MDU4MTgsImV4cCI6MjA2MTE4MTgxOH0.csy003hVKkW1u5O0Lqialc6EDKJ789S-RG_-OKyfczg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);